### PR TITLE
Make Spotify Wrapper

### PR DESCRIPTION
**Pull request by mpace965**
Makes a Spotify API caller wrapper method. Will automatically refresh a user's access token and update it in the db if they get a 401. Also changed /auth/spotify/test to return the value of hitting the /me route in Spotify. Try out different Spotify API methods with query params too!

### CODE REVIEW

**Comment by mattgfisch** [comment]
Pulled it down, played around with it, and it looks great! 

It's not really essential or part of the MVP, but I think as time goes on we should improve our error handling so that we display relevant messages to users as we attempt to resolve errors on our end (ex. "Sorry, there was an issue connecting to Spotify!"). Definitely don't need an error message for a 401, but something to think about for other error codes.

🚀

**Review by mattgfisch — APPROVED** [review]

**Comment by mpace965** [comment]
Right, I agree. I think that sort of error handling should be the responsibility of the calling code, because that code has more context about what exactly needs to be sent to the user. So the wrapper encapsulates the functionality of calling (or refreshing and calling) the Spotify API, and any failure along the way will throw an error. Then its up to the code calling the wrapper method to properly handle that error.

Also, I'm going to add a test so you can take a look at that too. I'll tag you again when its pushed.

**Comment by mattgfisch** [comment]
That approach makes much more sense than handling the error within the wrapper since the wrapper has no context. Good call 💯

**Comment by mpace965** [comment]
@mattgfisch 

Added sinon, a testing library which allows us to stub method calls and assert on them, and proxyquire, which is like a drop-in replacement for `require` that returns whatever value you give it instead of the module at the path it points to. In this case, we're using proxyquire to stub axios calls to the Spotify API as well as sequelize db operations.

I tested the following cases:
* happy path (caller gets response from Spotify API)
* unauthorized, but refreshed token path
* unauthorized, couldn't refresh token path

**Pull request merged**
