### PR TITLE
Set up react

### PR DESCRIPTION
**Pull request by mpace965**
Sets up React, and a bunch of other things. I got carried away, and should've done smaller pull requests. Also, I squashed all the commits into one so we don't have a bunch of commits in development.

* Sets up React, Webpack
* Makes linting pass in React files, and sets up environment specific linting (test, react/jsx)
* Sets up linting as a step in CI (best to set up eslint locally so your builds don't fail)
* Sets up webpack-dev-server, so that you never need to take down the server and rebuild to test out a React component. In fact, updating a React component will [make it refresh the browser automatically](https://youtu.be/ShSaGAjX4ic?t=180).
* Production builds will build to the `dist/js` directory
* Also, `npm install` has been moved back into the Dockerfile. Only `src` is volume mounted now. It was causing too many problems to volume mount the whole directory. However, the Dockerfile has been restructure to cache `npm install`. So if you don't make any changes to package.json, the entire build step will be cached.
* All of that `npm` stuff is now `yarn` stuff. Yarn is a different package manager for node, and it does a better job of locking in dependencies with `yarn.lock`. Its also seemingly better supported on CircleCI and docker. New versions of npm seem to crash. Read up on [Yarn](https://yarnpkg.com/en/)

That was a lot. Comment with questions and I'll follow up!

### CODE REVIEW

**Comment by mpace965** [comment]
Hmm, very odd build failure. I'm re-running it. If it persists, I'll take a look at it. But you should pull this down and play with it.

**Comment by mpace965** [comment]
I updated the `npm` version too, it may have something to do with that. I'll look into it.

**Review by mattgfisch — CHANGES_REQUESTED** [review]
The only thing that needs to be changed is that the base branch should be `development` instead of `master`. 

Other than that, it looks great! Your documentation is great on the PR, I agree with the switch to yarn, and Handlebars seems like the right choice. I pulled down the branch and branched off of it so I could test adding more partials, layouts, and controllers. Everything checks out and I feel comfortable with the set-up.

**Comment by mpace965** [comment]
Changed from master. We need to look into changing the default behavior.

**Review by mattgfisch — APPROVED** [review]

**Comment by mattgfisch** [comment]
🚢  And yea I'll try looking into the default behavior as well

**Pull request merged**
